### ISSUE TITLE
Three dot menus empty / not working

### ISSUE THREAD

**Issue by obetz** [openAIP/openaip#290] opened 2023-03-20 15:03 UTC
in the Aeronautical Data sub-entries, both three dot menus (kebab menus) don't yield any entries when clicked. See for the "Airtports" page:
![three_dot_menus](https://user-images.githubusercontent.com/24962139/226379577-ee96896a-d074-445b-9847-ca0930468db3.png)

**Comment by reskume** [comment] 2023-03-20 18:59
This is intended behavior. When window width decreases, the dot menu is used as an overflow menu that will then hold the export data button. The reason why this is not hidden by default is because content admins have additional menu items hidden in this dot-menu. I'll try to add a logic that will hide the dot-menu if either

- user lacks permissions to see the "hidden" items by default
- overflow is not needed

**Comment by reskume** [comment] 2023-03-27 19:15
Fixed with UI version v1.20.1

**Closed by reskume** 2023-03-27 19:15 UTC
Labels: enhancement, intended behavior
