### ISSUE TITLE
Support Reporting Points that are not attached to an airport

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#185] opened 2022-05-31 13:52 UTC
Dear all,

I wonder if openAIP supports (or could support) reporting points that are not attached to an airport. I believe these reporting points exist at the border of Germany and Poland (I understand that entry into Poland is only allowed via these points) and also in the Mediterranean, between Corsica and mainland France.

Best,

Stefan.

**Comment by reskume** [comment] 2022-06-02 07:13
Duplicate of #36 . Already planned. Still missing some good way to also easily allow editing/adding connected routes between those enroute waypoints.

**Closed by reskume** 2022-06-02 07:13 UTC
